export const FETCH_USER_REQUEST = 'FETCH_USER'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const FETCH_USER_REGISTER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_SIGN_IN_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_SIGN_OUT_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_UPDATE_SUCCESS = 'FETCH_USER_SUCCESS'